# Base configs
baseurl: "/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-blasdfhaskjd"

# UI configs
title: "From Dirk to Light"
subtitle: "by Dirk Recker"
author: "Dirk Recker"
header:
 title: "From Dirk to Light"
 subtitle: "by Dirk Recker"
footer:
 name: "Hey there, my name is Dirk"
 bio: "I enjoy making things for the home out of unexpected materials, all in my unmistakable steampunk style."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/dirk.recker"
  twitter: "https://twitter.com/ReckerD"
  instagram: "https://www.instagram.com/chicagorex/"
  dribbble: "https://dribbble.com/ramswaroop"
  linkedin: "https://www.linkedin.com/in/dirk-recker-394a36"
  github: "https://www.github.com/ramswaroop"
